### PR TITLE
Fix file pickers in Webview

### PR DESCRIPTION
**Pull request by FrozenAlex**
It also fixes the apk file picker
And adds logging js console.log to logger

It should allow us to have file picker parity with PC

### CODE REVIEW

**Comment by FrozenAlex** [comment]
ActivityResultCallbackRegistry was stolen from here, it's a pretty cool solution
https://github.com/dotnet/maui/blob/7be95d4e895af0f225f63c8a65fb04f2528e5fa3/src/Core/src/Platform/Android/ActivityResultCallbackRegistry.cs#L11

**Comment by FrozenAlex** [comment]
Those buttons no longer need to be hidden I guess

**Comment by AltyFox** [comment]
Thank you

**Comment by ComputerElite** [comment]
I trust you

**Pull request merged**
