### PR TITLE
Update QAVS to new mods repository.

### PR DESCRIPTION
**Pull request by AltyFox**
Did testing on my own device.  Found no issues.

### CODE REVIEW

**Comment by ComputerElite** [comment]
Looks good to me

**Comment by AltyFox** [comment]
Accidentally created a flaw.  Made a comment above before the pull request was accepted.  Accidentally placed a mod json file into the core mod qmod download section for the initial flow.
Awaiting comment from @DanTheMan827 <@244218712738103297> on the best way to achieve that, since the site generates the qmod in javascript as the button is clicked, no valid URL at the moment.

**Comment by DanTheMan827** [comment]
@AltyFox do you need a download parameter that would automatically do this?

**Comment by ComputerElite** [comment]
Ideally it'd be a file that can be downloaded

**Comment by DanTheMan827** [comment]
@AltyFox see https://github.com/ComputerElite/QuestAppVersionSwitcher/issues/80#issuecomment-2450054080

**Pull request merged**
